### PR TITLE
Don't fail when ptrace::detach returns ESRCH.

### LINKED ISSUE #29: Don't fail when `ptrace::detach()` returns an `ESRCH` error
If one of the threads we've suspended disappears while we're writing the minidump the call to `ptrace::detach()` in `PtraceDumper::resume_thread()` will fail setting `errno` to `ESRCH`. This is a completely benign error which we can ignore since we simply don't care about the state of the process/thread after we're done with it. The same applies to pretty much any other use of `pthread::detach()`, we could ignore this error for all of them.

### PR DESCRIPTION
**Pull request by afranchuk**
ESRCH indicates that the thread has disappeared while we had it stopped. We don't consider this an error.

Closes #29.

### CODE REVIEW

**Comment by afranchuk** [comment]
Note that we could probably add a test to cover this case; let me know if that's desirable (the existing tests fail on my local machine sometimes, I am going to look into that).

**Comment by gabrielesvelto** [comment]
If you have time to write a test that's always welcome! Also it seems that recent versions of clippy are complaining about [redundant casts](https://github.com/rust-minidump/minidump-writer/actions/runs/3849683432/jobs/6583915787), could you address it in a separate commit within this PR? Thanks for your contribution!

**Review by gabrielesvelto — APPROVED** [review]
Actually never mind the test, it would be highly timing dependent and we already have a way of detecting if this work in our usage in Firefox. This LGTM.

**Comment by gabrielesvelto** [comment]
I fixed the clippy issues after merging your PR, I didn't want to waste your time on them given they were trivial. As for the test I thought about it and it's a lot of work for little benefit: it's a scenario we routinely hit in production and we have a dedicated path for handling errors. If it doesn't work as expected we'll see it in production, if it works then the error will be gone and we get more minidumps. So there's no downsides to not having test coverage.

**Pull request merged**
